"""Generate CONCEPTS.md -- the complete index of `[HARNESS:*]` tags.

    uv run python scripts/concepts.py          # regenerate CONCEPTS.md
    uv run python scripts/concepts.py --check  # CI: fail if stale or a tag breaks the rules

The tags are the code's own map of where each harness concept is implemented
(convention in CLAUDE.md). The learning guide in docs/learn/ is the curated
route through them; this file is the exhaustive list, with file:line links.
"""

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "CONCEPTS.md"
SCAN_DIRS = ("opspilot", "evals", "scripts", "tests", ".github")
SCAN_SUFFIXES = {".py", ".yml", ".yaml", ".html"}
MAX_BLOCK_LINES = 5

# Pillar order follows a run: what drives it, what it can touch, what it's told,
# what stops it, what records it, what keeps it reliable, how it's judged.
PILLARS: dict[str, str] = {
    "LOOP": "The agent loop and the outer loops that start it",
    "TOOLS": "Tool contracts: what the agent can call",
    "ENV": "The sandboxed environment the tools act on",
    "CONTEXT": "What the model is told, and how much of it",
    "MEMORY": "What persists between model calls and across runs",
    "PERM": "Permissions: what each role may do",
    "GUARD": "Guardrails: injection defense, scope, cost and input checks",
    "HITL": "Human-in-the-loop approvals",
    "OBS": "Observability: traces, metrics, cost",
    "AUDIT": "The tamper-evident audit log",
    "ORCH": "Reliability: retries, normalized clients, idempotency",
    "EVAL": "Evals: datasets, record/replay, graders, gates",
}
TAG_RE = re.compile(r"\[HARNESS:([A-Z]+)\]\s*(.*)")


@dataclass(frozen=True)
class Tag:
    pillar: str
    title: str
    path: str  # repo-relative, forward slashes
    line: int
    block_lines: int
    has_why: bool


def _block(lines: list[str], i: int) -> list[str]:
    """The comment block a tag line starts: contiguous `#` lines, or (inside a
    docstring) contiguous non-blank lines up to the closing quotes."""
    first = lines[i].strip()
    block = [lines[i]]
    j = i + 1
    while j < len(lines):
        s = lines[j].strip()
        if first.startswith("#") and not s.startswith("#"):
            break
        if not first.startswith("#") and (not s or '"""' in s):
            break
        block.append(lines[j])
        j += 1
    return block


def scan(root: Path = ROOT) -> list[Tag]:
    tags: list[Tag] = []
    for directory in SCAN_DIRS:
        for path in sorted((root / directory).rglob("*")):
            if path.suffix not in SCAN_SUFFIXES or "__pycache__" in path.parts:
                continue
            lines = path.read_text().splitlines()
            for i, line in enumerate(lines):
                match = TAG_RE.search(line)
                if match is None:
                    continue
                block = _block(lines, i)
                tags.append(
                    Tag(
                        pillar=match[1],
                        title=match[2].strip(),
                        path=path.relative_to(root).as_posix(),
                        line=i + 1,
                        block_lines=len(block),
                        has_why=any("WHY" in b for b in block),
                    )
                )
    return tags


def violations(tags: list[Tag]) -> list[str]:
    problems = []
    for t in tags:
        where = f"{t.path}:{t.line}"
        if t.pillar not in PILLARS:
            problems.append(f"{where}: unknown tag [HARNESS:{t.pillar}]")
        if t.block_lines > MAX_BLOCK_LINES:
            problems.append(f"{where}: {t.block_lines} lines (max {MAX_BLOCK_LINES})")
        if not t.has_why:
            problems.append(f"{where}: no WHY")
        if not t.title:
            problems.append(f"{where}: empty first line (it becomes the index entry)")
    return problems


def render(tags: list[Tag]) -> str:
    out = [
        "# Harness concepts index",
        "",
        "<!-- Generated by scripts/concepts.py -- do not edit by hand. -->",
        "",
        "Every place a harness concept is implemented carries a `[HARNESS:<PILLAR>]` comment.",
        "This is the complete list, generated from those comments. For a guided route through",
        "the same ideas, start at [`docs/learn/`](docs/learn/).",
        "",
        "| Pillar | What it covers | Tags |",
        "|---|---|---|",
    ]
    by_pillar = {p: [t for t in tags if t.pillar == p] for p in PILLARS}
    for pillar, description in PILLARS.items():
        out.append(f"| [{pillar}](#{pillar.lower()}) | {description} | {len(by_pillar[pillar])} |")
    for pillar, description in PILLARS.items():
        out += ["", f"## {pillar}", "", f"_{description}._", ""]
        if not by_pillar[pillar]:
            out.append("_No tags yet._")
        for t in by_pillar[pillar]:
            title = t.title.replace("|", "\\|")
            out.append(f"- [{title}]({t.path}#L{t.line}) — `{t.path}:{t.line}`")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if stale or a tag is invalid")
    args = parser.parse_args(argv)

    tags = scan()
    problems = violations(tags)
    content = render(tags)
    if args.check:
        stale = not OUTPUT.exists() or OUTPUT.read_text() != content
        for problem in problems:
            print(f"tag rule: {problem}")
        if stale:
            print("CONCEPTS.md is stale -- run: uv run python scripts/concepts.py")
        return 1 if problems or stale else 0
    if problems:
        for problem in problems:
            print(f"tag rule: {problem}")
        return 1
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.name}: {len(tags)} tags across {len(PILLARS)} pillars")
    return 0


if __name__ == "__main__":
    sys.exit(main())
