from typing import Any, Protocol

from opspilot.store.models import ApprovalDoc, AuditDoc, RunDoc, SpanDoc


class Store(Protocol):
    """Persistence for runs, spans, audit entries, and approvals.

    Two implementations share this interface: MemoryStore (tests, and the
    CLI's default -- no external service required) and MongoStore (real
    persistence, selected via OPSPILOT_STORE=mongo). Nothing outside
    opspilot/store/ should import pymongo directly or know which backend
    is active -- that's the point of depending on this Protocol instead.
    """

    async def ensure_indexes(self) -> None: ...

    async def insert_run(self, run: RunDoc) -> None: ...
    async def get_run(self, run_id: str) -> RunDoc | None: ...
    async def list_runs(self) -> list[RunDoc]: ...
    async def update_run(self, run_id: str, updates: dict[str, Any]) -> None: ...

    async def insert_span(self, span: SpanDoc) -> None: ...
    async def list_spans(self, run_id: str) -> list[SpanDoc]: ...

    async def insert_audit(self, entry: AuditDoc) -> None: ...
    async def list_audit(self, run_id: str | None = None) -> list[AuditDoc]: ...
    async def get_last_audit(self) -> AuditDoc | None: ...

    async def insert_approval(self, approval: ApprovalDoc) -> None: ...
    async def get_approval(self, approval_id: str) -> ApprovalDoc | None: ...
    async def update_approval(self, approval_id: str, updates: dict[str, Any]) -> None: ...
    async def list_pending_approvals(self) -> list[ApprovalDoc]: ...
